
const animals = {
    AmazonRiverDolphin: {
        id: 1,
        name: `Amazon River dolphin (Inia geoffrensis)`,
        description: `The boto, or Amazon River dolphin, is probably the best-known of the river dolphins. These animals are moderately robust, and have long beaks and steep bulbous foreheads, which are capable of changing shape. There is no true dorsal fin, but only a dorsal ridge that is low and wide-based. The flippers are large and triangular, with blunt tips, and the flukes have a concave trailing edge that is often ragged. The eyes are small, but not as small as those of the Ganges River dolphin or Indus River dolphin. Botos are grey to pink above and lighter below; some individuals are totally pink. In general, young animals are mostly uniform dark grey; they become progressively more pinkish with age. The extreme colour is so unique that the boto is often called the pink dolphin. The mouth is lined with 23 to 35 stout teeth in each row. This is the only species of cetacean with differentiated teeth; those at the front of the jaw are typically conical, but those near the rear are flanged on the inside.`,
        size: `Adult size ranges to 2.3 m (females) or 2.8 m (males). Males can reach maximum weights of 160 kg. At birth, boto are about 80 cm long.`,
        distribution: `Boto are endemic to the Amazon and Orinoco drainage basins of South America. Their distribution extends to the upper reaches (impassible falls or rapids) of these rivers and their tributaries in Guyana, Colombia, Ecuador, Peru, and Bolivia, as well as the lower reaches in Brazil and Venezuela. They are found widely not only in the main river channels, but also in smaller tributaries, lakes, and (seasonally) the flooded forest.`,
        behavior: `Groups of up to 12 to 15 have been observed, but most boto are seen singly or in small groups. They generally move slowly, and surface at a shallow angle, showing the top of the head and the dorsal ridge. Their responses to humans can range from shyness to curiosity. In Brazil, births apparently occur in May to July, the season of peak flooding. These animals feed on a large variety of fishes, generally near the bottom. Some of their prey have hard outer shells, and dolphins have been observed breaking up their larger prey before swallowing. They sometimes feed in a coordinated manner, occasionally with Sotalia.`,
        exploitation: `Boto are threatened by various activities, among them are incidental catches in fisheries, damming of rivers associated with hydroelectric development, deforestation, and pollution from mercury mining operations. Significant numbers have been taken for the aquarium trade. Despite these problems, boto are still abundant in many parts of their range. Superstitions surrounding this species provide protection from hunting in many areas of its range.`,
        confusedWith: `The only other dolphin that inhabits the range of the boto is Sotalia. This latter species is much smaller, has a taller dorsal fin, and more spritely dolphin-like movements.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/AmazonRiverDolphin/amazon-river-dolphin.jpg`
    },
    atlanticHumpBackedDolphin: {
        id: 2,
        name: `Atlantic hump-backed dolphin`,
        description: `Atlantic hump-backed dolphins have a long, distinct beak, broad flippers with rounded tips, and a moderately deepened tail stock. The dorsal fin is variable in shape, but generally emerges from a wide hump or ridge on the animal's back. Although this species is poorly known, it is probably sexually dimorphic, like the Indo-Pacific hump-backed dolphin. Tooth counts are 27 to 31 per upper tooth row, and 26 to 30 per lower row.`,
        colouration: `Animals are slate grey on the sides and back, and light grey below.`,
        confusedWith: `The bottlenose dolphin also inhabits the inshorerange of the Atlantic hump-backed dolphin. The 2 can be distinguished by differences in beak length, dorsal-fin shape (including the hump), and coloration.`,
        size: `Adults are up to about 2.8 m in length, and weigh up to 284 kg. Length at birth is thought to be about 1 m.`,
        distribution: `Atlantic hump-backed dolphins occur off tropical to subtropical West Africa, from Mauritania south to at least Cameroon, possibly to northern Angola. They are found primarily in estuarine and coastal waters. Some hump-backed dolphins inhabit rivers, such as the Niger, but it is not known if there are separate freshwater populations.`,
        behavior: `Groups generally contain 5 to 7 individuals, occasionally up to 25 animals. Groups often feed very near shore. These animals generally do not bowride. Breeding has been documented in March and April, but the breeding season may be more protracted. Hump-backed dolphins feed on schooling fishes and, contrary to some descriptions, probably do not eat vegetable matter. Off the coast of Mauritania, fishermen using beach seines cooperate with Atlantic hump-backed and bottlenose dolphins to capture mullet.`,
        exploitation: `Hump-backed dolphins are taken in beach seines and shark netsin Senegal. There is apparently also some direct capture of small cetaceans in West Africa for human consumption. Also of concern are the effects of offshore foreign fishing and mangrove destruction.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/atlanticHumpBackedDolphin/atlantic-hump-backed-dolphin.jpg`
    },
    atlanticSpottedDolphin: {
        id: 3,
        name: `Atlantic spotted dolphin (Stenella frontalis)`,
        description: `The Atlantic spotted dolphin, in many ways, tends to resemble the bottlenose dolphin more than it does the pantropical spotted dolphin. In body shape, it is somewhat intermediate between the 2, with a moderately long, but rather chunky, beak. There is a distinct crease between the melon and beak. There is much developmental variation in the colour pattern. Atlantic spotted dolphins begin life with unspotted background coloration. Young animals look much like slender bottlenose dolphins, with a dark cape, light grey sides and spinal blaze (variable in its development), and white belly. Large spotting on both dorsal and ventral surfaces progresses as the animal ages; some individuals become so heavily spotted that the cape margin and spinal blaze are obscured. However, in some populations, adults are essentially unspotted (these are generally in offshore areas). There are 30 to 42 pointed teeth in each tooth row.`,
        confusedWith: `Atlantic spotted dolphins can be most easily confused with bottlenose dolphins and sometimes with pantropical spotted dolphins. The differences in size and robustness are good clues, but may require a trained eye to distinguish in many sightings at sea. Heavy spotting is a good characteristic for Atlantic spotted dolphins; however, some may be nearly unspotted and some bottlenose dolphins may have spotting and blotches on the belly and sides. Pantropical spotted dolphins also may be difficult to distinguish, but attention to body robustness, snout shape, and colour pattern differences will allow them to be separated. Only the coastal form of the pantropical spotted dolphin is likely to appear very similar to the Atlantic spotted dolphin, but the former is only known from the eastern Pacific.`,
        size: `Adults are up to 2.3 m long and 143 kg in weight. Newborn Atlantic spotted dolphins are 0.8 to 1.2 m long.`,
        distribution: `This species is found only in the Atlantic Ocean, from southern Brazil to New England in the west, and to the coast of Africa in the east (the exact limits off West Africa are not well known). Their tropical to warm temperate distribution is mostly over the offshore continental shelf, but Atlantic spotted dolphins also inhabit some deep oceanic waters.`,
        behavior: `Small to moderate groups, generally of less than 50 individuals, are characteristic of the Atlantic spotted dolphin. Coastal groups usually consist of 5 to 15 animals. These are acrobatic animals and they are known to be avid bowriders. Studies of Atlantic spotted dolphins off the Bahamas that allow people to swim with them show that these animals have a fluid group structure, like that of bottlenose dolphin and other small dolphins. There is not much known of the species' life history, but tropical populations would be expected to have a protracted breeding season. A wide variety of fishes and squids are taken by this species.`,
        exploitation: `Atlantic spotted dolphins are taken in a direct fishery for small cetaceans in the Caribbean. Direct takes may also occur off the Azores and off West Africa. Some are probably also taken incidentally in tuna purse seines off the West African coast. However, there are not reliable estimates of the number of animals taken in any of these fisheries.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/atlanticSpottedDolphin/atlantic-spotted-dolphin.jpg`
    },
    atlanticWhiteSidedDolphin: {
        id: 4,
        name: `Atlantic white-sided dolphin (Lagenorhynchus acutus)`,
        description: `Atlantic white-sided dolphins have the typical Lagenorhynchus body shape which is a stocky body with a short thick snout and tall falcate dorsal fin. The tail stock is strongly deepened. The colour pattern is complex. The back and upper sides, upper jaw, dorsal fin, flippers, and flukes are black or dark grey, and a dark line runs backwards from the beak and surrounds the eye. The lower jaw and belly, as far as the urogenital area, are white. In between, the sides from just ahead of the eye to the base of the flukes are light grey. Along the upper margin of the grey side is a white patch from below the dorsal fin to midway along the tail stock. There is another narrow band, this one ochre in colour, at the lower margin of the dark upper flank, from the middle of the tail stock to just in front of the flukes. Each tooth row contains 30 to 40 pointed teeth.`,
        confusedWith: `Confusion is most likely with the white-beaked dolphin, which shares a nearly identical range. The 2 can be distinguished most easily by colour-pattern differences.`,
        size: `Adult Atlantic white-sided dolphins reach 2.8 m (males) or 2.5 m(females) in length and about 235 kg (males) and 182 kg (females) in weight. Newborns are 1.1 to 1.2 m.`,
        distribution: `Atlantic white-sided dolphin are found in cold temperate to subpolar waters of the North Atlantic, from about New England in the west and France in the east, north to southern Greenland, Iceland, and southern Norway. They rarely enter the Baltic Sea. The preferred habitat appears to be deep waters of the outer continental shelf and slope.`,
        behavior: `Herds of up to several hundred are seen, and there is some age and sex segregation of herds. Older immature individuals are not generally found in reproductive herds of mature females and young. Atlantic white-sided dolphins are lively and acrobatic. Much of what we know of this species' biology comes from examination of individuals from mass strandings. Calves are born in summer, with a peak in June and July. Atlantic white-sided dolphins feed on small schooling fish and squid. They often feed in association with largewhales.`,
        exploitation: `Some hunting for this species occurred in the past, especially in Norway. Some are still taken in Greenland, the Faeroe Islands, and eastern Canada. Incidental kills in gillnets and other fishing gear is known from both sides of the Atlantic. Despite this exploitation, Atlantic white-sided dolphins are very abundant, at least off the northeast coast of North America.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/atlanticWhiteSidedDolphin/atlantic-white-sided-dolphin.jpg`
    },
    baiji: {
        id: 5,
        name: `Baiji (Lipotes vexillifer)`,
        description: `Outside of China, very little was known of the baiji's biology until recently. These animals are moderately robust, with long, slightly upturned beaks, rounded melons, low triangular dorsal fins (set about two-thirds of the way back from the snout tip), and broad rounded flippers. The eyes are small, compared to those of oceanic dolphins, but not as small as those of Platanista sp. Baiji, or Chinese river dolphins, are predominantly dark bluish grey above and light grey to white below. There are light brushings on the side of the face and the side of the tail stock. Each toothrow contains 31 to 38 conical teeth`,
        confusedWith: `The only other small cetacean in the baiji's range is the finless porpoise, which can be readily distinguished by its darker coloration and absence of a dorsal fin.`,
        size: `Male baiji reach sizes of 2.3 m and 135 kg, and females reach 2.6 m and over 240 kg. Apparently, newborn baiji are less than 95 cm in length.`,
        distribution: `The baiji is found only in the middle and lower reaches of the Yangtze River in China. Baiji may occasionally enter large lakes during intense flooding. The range was formerly broader.`,
        behavior: `Groups of 2 to 6 baiji are most commonly seen, but aggregations of up to 13 animals sometimes form. These dolphins are generally shy of boats, and their surfacings are shallow, often exposing only the top of the head, dorsal fin, and a small part of the back. The peak calving season appears to be February to April. A large variety of fish species make up the diet of the baiji.`,
        exploitation: `With the possible exception of the vaquita, this is the most endangered of all cetaceans. The major source of mortality for baiji appears to be incidental catches in fishing gear, especially the so-called “rolling hooks” that are used to snag fish along the bottom of the Yangtze. Other threats include vessel collisions and disturbance, pollution, construction of dams, overfishing of prey species, and general modification of habitat through various human activities. Although China has declared the baiji a “Protected Animal of the First Order,” there is still much uncertainty about the future of this species.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/baiji/baiji.jpg`
    },
    bhulan: {
        id: 6,
        name: `Bhulan (Platanista minor)`,
        description: `Indus River dolphins, or bhulan, are almost identical in external appearance to Ganges River dolphins. In fact, some researchers believe that the 2 types would be most appropriately classified as subspecies of Platanista gangetica. The most distinctive characteristics are the robust body, low dorsal fin, long beak, small eyes, longitudinal blowhole, and elongated front teeth.`,
        confusedWith: `Although their ranges generally overlap only in a small portion of the lower Indus, Indus River dolphins might be confused with Irrawaddy dolphins, finless porpoises, bottlenose dolphins, and Indo-Pacific hump-backed dolphins. The dorsal fins of bottlenose and hump-backed dolphins, complete lack of a dorsal fin in finless porpoises, and absence of a beak in Irrawaddy dolphins should make them distinguishable. Also, bottlenose and hump-backed dolphins are much larger.`,
        size: `Indus River dolphins probably grow slightly smaller than the maximum sizes of 2.6 m (females) and 2.2 m (males) for Ganges River dolphins. Length at birth is between 70 and 90 cm.`,
        distribution: `Though formerly more widely distributed in the Indus and some of its tributaries, the range is now restricted to the middle and lower Indus River. It is centered between Jinnah and Kotri barrages.`,
        behavior: `Although most commonly seen singly or in very small groups, Indus River dolphins have been reported in loose aggregations of up to 30 individuals. Like their relatives in the Ganges River, they often swim on their sides and appear to navigate mainly with the aid of echolocation. There is almost nothing known of the reproductive biology of this species. Newborns have been observed in April and May. Indus River dolphins feed on prawns and several species of fish. They may do much of their feeding on or near the bottom.`,
        exploitation: `The Indus River dolphin is now extirpated in many parts of its former range. Both incidental and direct catches, as well as various forms of habitat destruction (including damming, diversion, and contamination of rivers) represent threats to the survival of the Indus River dolphin.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/bhulan/bhulan.jpg`
    },
    blackDolphin: {
        id: 7,
        name: `Black dolphin (Cephalorhynchus eutropia)`,
        description: `This insufficiently known dolphin is robust, with a short, poorly defined beak. The dorsal fin is moderately low and rounded, and the flippers have rounded tips, much like those of other members of the genus. The body is mostly grey, with a darker grey band extending from the blowhole to above the eye. There is often darker grey on the sides of the face, and in a wide band from around the eye to the flipper. On the belly are large white patches from behind the flippers to the urogenital area, and from ahead of the flippers to the snout tip. These patches are separated by a dark grey band between the flippers. There are also small white patches in the axillae, and thin grey patches around the urogenital area (the latter are sexually and individually variable). Black dolphins have 29 to 34 small pointed teeth in each row.`,
        confusedWith: `Black dolphins can be confused with Commerson's dolphins around the southern tip of South America. The large white areas on Commerson's dolphins are the best clue. Burmeister's porpoises may also be confused with this species. Here, dorsal-fin shape will be the best character to distinguish them.`,
        size: `Adults of this species are up to at least 1.7 m (size at sexual maturity has not been sufficiently documented). Black dolphins reach weights of up to 63 kg. Length at birth is unknown, but is probably somewhat less than 1 m.`,
        distribution: `This dolphin is found only on the Chilean coast, from 30°S to the tip of South America. As is true of other members of the genus, it is found in shallow coastal waters, and enters estuaries and rivers.`,
        biology: `Until recently, there have been very few sightings of these animals by researchers. Groups tend to be small, between 2 and 15 members, but aggregations of up to 400 have been recorded. Although active and very conspicuous, they tend to be shy and difficult to approach, but may occasionally ride bow waves. Most sightings of newborn black dolphins have been from October to April. Black dolphins feed on fish, cephalopods, and crustaceans.`,
        exploitation: `Black dolphins are taken both incidentally in gillnets (and occasionally in seines) and directly by harpoon in a fishery for crab bait off southern Chile. Incidental catches are also sometimes utilized for oil and human consumption. The effects of these fisheries on black dolphin population(s) are not known.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/blackDolphin/black-dolphin.jpg`
    },
    bottlenoseDolphin: {
        id: 8,
        name: `Bottlenose dolphin (Tursiops truncatus)`,
        description: `The bottlenose dolphin is probably the most familiar of the small cetaceans because of its coastal habits, prevalence in captivity worldwide, and frequent appearance on television and in advertising. It is a large, relatively robust dolphin, with a short to moderate-length stocky snout that is distinctly set off from the melon by a crease. The dorsal fin is tall and falcate, and set near the middle of the back. Colour varies from light grey to nearly black on the back and sides, fading to white (sometimes with a pinkish hue) on the belly. The belly and lower sides are sometimes spotted. There is a dark stripe from eyeto flipper, and a faint dorsal cape on the back (and sometimes an indistinct spinal blaze), generally only visible at close range. Often, there are brushings of grey on the body, especially on the face, and from the apex of the melon to the blowhole. Bottlenose dolphins have 18 to 26 pairs of robust teeth in each jaw. In older animals, many of these may be worn down or missing. In many areas of the world, such as South Africa, the Northwest Atlantic, Peru, and the eastern North Pacific, there appear to be 2 forms, a coastal type and an offshore type; however, the taxonomy of bottlenose dolphins is still somewhat confused, due to the great extent of geographical variation.`,
        confusedWith: `Bottlenose dolphins can be mistaken for several other species of dolphins, depending on the area. There can be confusion in the tropical Atlantic with Atlantic spotted dolphins, along the east coast of South America with dolphins of the genus Sotalia, and in the Indo-Pacific and off West Africa with hump-backed dolphins. When seen from a distance, they could also be confused with Risso's or rough-toothed dolphins. Such confusion will generally only occur when the animals are not seen well; in most situations, bottlenose dolphins are distinctive.`,
        size: `Adults range from 1.9 to 3.8 m, with males somewhat larger than females. There is incredible variation between different populations. Maximum weight is at least 650 kg, although most animals are much smaller. Length at birth is about 1 to 1.3 m.`,
        distribution: `Bottlenose dolphins are found primarily in coastal and inshore regions of tropical and temperate waters of the world. Population density appears to be higher nearshore. Bottlenose dolphins are known also to inhabit some pelagic waters, such as those in the eastern tropical Pacific. Except for their occurrence around the United Kingdom and northern Europe, they generally do not range poleward of 45° in either hemisphere.`,
        behavior: `More is known of the biology of this species than of any other dolphin. Group size is commonly less than 20, but large herds of several hundred are often seen offshore. Bottlenose dolphins are commonly associated with other cetaceans, and hybrids with other species are known from both captivity and in the wild. Based on a number ofstudies of nearshore populations, bottlenose dolphins seem to live in relatively open societies. In some areas, dolphins have limited home ranges; in others, they are migratory, generally ranging further. Mother and calf bonds and some other associations may be strong, but individuals may be seen from day-to-day with a variety of different associates. The bottlenose dolphin is the most common species of dolphin held in captivity. It has proven highly adaptable and is easily trained. Much of what we know of the general biology of dolphins comes from studies of bottlenose dolphins, both in captivity and in the wild. Bottlenose dolphins are sometimes active (especially when feeding or socializing), often slapping the water with their flukes, leaping, and performing other aerial behaviours. Spring and summer or spring and autumn calving peaks are known for most populations. They are opportunistic feeders, apparently taking whatever suitable prey is most abundant at the time. Feeding behaviour is varied, ranging from cooperative foraging on schooling fish, to individually chasing fish onto mudbanks, to feeding behind shrimp trawlers and other fishing operations.`,
        exploitation: `Both incidental and direct exploitation of bottlenose dolphins are known to occur, generally at low to moderate levels. The largest direct kills have traditionally been in the Black Sea, where Russian and Turkish hunters apparently have reduced local populations. Bottlenose dolphins also are taken elsewhere in gillnets, shark nets, shrimp trawls, and purse seines (the latter in the multi-national tuna purse seine fishery of the eastern tropical Pacific). They also are occasional victims of harpoon and drive fisheries. Live capture removals have had considerable effects on some populations, such as those in the Gulf of Mexico and U.S. southeast coast.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/bottlenoseDolphin/bottlenose-dolphin.jpg`
    },
    burmeistersPorpoise: {
        id: 9,
        name: `Burmeister's porpoise (Phocoena spinipinnis)`,
        description: `The unique dorsal fin of Burmeister's porpoise rises at a very shallow angle from behind the midpoint of the back, and the trailing edge is straight to convex. Additionally, there are tubercles along the leading edge of the fin (this characteristic gave the species its scientific name). Other than this, the species has a rather typical phocoenid body form, with a blunt, nearly beakless head and broad-based flippers with rounded tips. Coloration is dark charcoal to grey, with lighter grey streaks on the chin and belly. Burmeister's porpoises have dark eye patches, dark lips, and dark chin-to-flipper stripes (well-defined by lighter areas above and below). These flipper stripes are asymmetrical; they are more narrow and extend further forward on the right side. Teeth number 10 to 23 in each upper tooth row and 14 to 23 in each lower row. As in other phocoenids, the teeth are spatulate.`,
        confusedWith: `Burmeister's porpoises can be confused with South American fur seals and South American sea lions, which often stick their flippers in the air (these can look like Burmeister's porpoise dorsal fins). Differences in coloration, dorsal-fin shape, and swimming style should allow Burmeister's porpoises to be distinguished easily from Commerson's dolphins and spectacled porpoises, and head shape will be the best characteristic to allow distinction from franciscana.`,
        size: `Most adults are up to 1.85 m in length, although animals from Uruguay up to 2 m have been recorded. Maximum weight is about 85 kg. Newborns are 0.8 to 0.9 m.`,
        distribution: `Burmeister's porpoises are distributed in coastal waters of South America, from southern Brazil, south to Tierra del Fuego, and north to northern Peru.`,
        behavior: `Very little is known about the natural history of this species. Most sightings are of less than 6 individuals, but aggregations of up to 70 have been reported. Behaviour of this species is inconspicuous; they breath with little surface disturbance. There appears to be a protracted summer birth peak; most births in Peru apparently occur in late summer to autumn. Feeding is on fish, such as anchovies and hake, as well as squid.`,
        exploitation: `Burmeister's porpoises are caught mostly in gillnets. They are taken, apparently in small numbers, in shark gillnets in Uruguay, fish (and until recently, king crab) gillnets around Tierra del Fuego, and gillnets for a variety of fish off Chile and Peru (by far, the largest kills). Additionally, they may be caught in direct fisheries for dolphins, using mostly gillnets, which have prospered in recent years in Peru, and to a lesser extent, Chile.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/burmeistersPorpoise/burmeisters-porpoise.jpg`
    },
    centralAmericanSpinnerDolphin: {
        id: 10,
        name: `Central American spinner dolphin (Stenella longirostris)`,
        description: `The spinner dolphin is a slender dolphin, with an extremely long, thin beak. Also, the head is very slender at the apex of the melon. The dorsal fin ranges from slightly falcate to erect and triangular. In adult males of some stocks, the dorsal fin may become so canted forward that it looks as if it were stuck on backwards, and the tail stock may become very deepened, with an enlarged post-anal keel of connective tissue. Spinner dolphins generally have dark eye-to-flipper stripes and dark lips and beak tips. There are 3 subspecies known. The individuals of most spinner dolphin stocks in the world have a three- part colour pattern (dark grey cape, light grey sides, and white belly) and only minor differences in appearance of males and females. These animals (illustrated above) are called Gray's spinner dolphins (S. l. longirostris). In the eastern tropical Pacific, there are 3 other forms. Eastern spinner dolphins (S. l. orientalis) have a monotone steel grey colour pattern, with white only as patches around the genitals and axillae. They have the most exaggerated sexual dimorphism. Central American spinner dolphins (S. l. centroamericana), previously called Costa Rican spinners, are poorly known, but appear to have a similar colour pattern, although it may lack the white ventral patches. A third type of spinner dolphin in the eastern tropical Pacific, often called the whitebelly spinner dolphin, appears to represent a hybrid between eastern spinner and Gray's spinner dolphins. Whitebelly spinners are more robust, with a two-part colour pattern and less exaggerated sexual dimorphism than the other stocks in the eastern tropical Pacific. Geographical forms of spinner dolphins have not been well described for most areas, with the exception of the eastern Pacific; although a dwarf form has been described from the Gulf of Thailand. Animals of the above described forms, or other undescribed stocks, may exist elsewhere as well. In spinner dolphins, there are 45 to 62 pairs of very fine, pointed teeth in each jaw. This is more than in almost any other cetacean species.`,
        confusedWith: `From a distance, other long-snouted oceanic dolphins can look like spinner dolphins. Spinner dolphins are most likely to be confused with clymene dolphins in the Atlantic, but careful attention to colour pattern differences and head and body shape differences will allow them to be distinguished.`,
        size: `Newborn spinner dolphins are about 75 to 80 cm long; adults reach 2 m (females) and 2.4 m (males). They reach weights of at least 77 kg. Eastern spinner dolphins are the smaller and Central American spinnerdolphins the larger of the subspecies in the eastern tropical Pacific.`,
        distribution: `The range of the spinner dolphin is nearly identical to that of the pantropical spotted dolphin, encompassing oceanic tropical and subtropical zones in both hemispheres. Limits are near 40°N and 40°S.`,
        behavior: `The spinner dolphin is named for its habit of leaping from the water and spinning up to 7 times on its long axis, before falling back to the water. This is one of the most aerial of all dolphins. Herd sizes range from less than 50 up to several thousand. Associations with pantropical spotted dolphins are common in the eastern tropical Pacific. Calving peaks in different populations range from late spring to autumn. Spinner dolphins of most populations feed predominantly at night, on mid-water fish and squid, and rest during much of the day. Their association with pantropical spotted dolphins and yellowfin tuna results in their entanglement in tuna purse seines in the eastern tropical Pacific.`,
        exploitation: `Both the whitebelly and eastern spinner forms have been heavily involved in the tropical Pacific tuna purse seine fishery. The numbers of eastern spinners have been reduced significantly in the last few decades by this fishing practice. Catches of spinner dolphins also occur in the Caribbean, Australia, Japan, Thailand, the Philippines, and Sri Lanka; in this last area up to 15,000 are killed each year in gillnets and by hand-harpooning. There are likely to be fisheries interactions off West Africa.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/centralAmericanSpinnerDolphin/central-american-spinner-dolphin.jpg`
    },
    clymeneDolphin: {
        id: 11,
        name: `Clymene dolphin (Stenella clymene)`,
        description: `The clymene dolphin is externally similar to the spinner dolphin, but is smaller and more robust, with a much shorter and stockier beak. The dorsal fin is slightly more falcate, as opposed to the often very triangular dorsal fins of spinner dolphins. Despite these external similarities with the spinner dolphin, skull morphology indicates that the clymene dolphin may be closely related to the striped dolphin. A three-part colour pattern, with a dark grey cape, light grey sides, and white belly, is characteristic of this species. The cape dips in 2 places, above the eye, and below the dorsal fin. The beak is mostly light grey, but the lips and beak tip are black. There is also a dark stripe on the top of the beak, from the tip to the apex of the melon, and often a dark “moustache” marking on the middle of the top of the beak. The eye is also surrounded by black, and a dark grey stripe runs from the eye to the flipper. Tooth counts are generally much lower than in spinner dolphins: 38 to 49 teeth per row. They are slender and pointed.`,
        confusedWith: `Clymene dolphins are most easily confused with spinner dolphins, but are more robust, with shorter stubbier beaks. Also, the colour pattern is slightly different; the 2 dips in the cape and the dark line (and often a “moustache”) on top of the beak will allow clymene dolphins to be distinguished. The body shape of clymene dolphins also closely resembles that of short-beaked (offshore) forms of the common dolphin, as does the colour pattern in a superficial way. Common dolphins can best be distinguished by their hourglass pattern, cape that forms a V below the dorsal fin, chin-to-flipper stripe, and absence of a “moustache.”`,
        size: `So far, clymene dolphins are known to reach at least 2.0 m in length and sexual maturity is reached by about 1.8 m. Newborn length is unknown, but is less than 1.2 m. This species reaches weights of at least 85 kg.`,
        distribution: `The clymene dolphin is found only in the tropical and subtropical Atlantic Ocean, including the Caribbean Sea and Gulf of Mexico. There are records as far north as New Jersey on the U.S. east coast and as far south as southern Brazil. The limits on the West African coast are not well known. This is a deep water oceanic species, not normally seen near shore.`,
        behavior: `Very little is known of the clymene dolphin's natural history. Schools tend to be much smaller than those of spinner dolphins (generally lessthan 50 animals). They are known to associate with other species of dolphins. These quick and agile dolphins ride bow waves, and have been reported to spin on the long axis. Clymene dolphins feed on small fish and squid at moderate depths, presumably mainly at night.`,
        exploitation: `In the Caribbean, clymene dolphins appear, at least occasionally, to be taken in the Lesser Antilles small cetacean fishery, and in gillnets. They may be one of the species taken in tuna purse seines in the eastern tropical Atlantic.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/clymeneDolphin/clymene-dolphin.jpg`
    },
    commersonsDolphin: {
        id: 12,
        name: `Commerson's dolphin (Cephalorhynchus commersonii)`,
        description: `The stocky Commerson's dolphin is similar in body shape to porpoises (phocoenids), as are other species of the genus. The head is blunt, with little or no beak and a relatively straight mouthline. The dorsal fin is moderately low and rounded, rising at a shallow angle from the back; the flippers and flukes have rounded tips. The colour pattern is strikingly contrasted black and white (dark grey and light grey in the Kerguelen Islands). There is a white band that completely encircles the body dorsally from just behind the blowhole to in front of the dorsal fin, and ventrally from behind the flippers to behind the genital area. There is a large white patch on the throat, and a black oval to heart-shaped patch around the genitals that varies in shape between males and females (females generally have the heart-shaped patch pointing forward, males pointing backward). The rest of the animal is black, including the top of the head, flippers, dorsal fin, and flukes. Newborn animals have a muted pattern of mostly grey tones, as do many small cetaceans. There are 28 to 35 small, pointed teeth in each tooth row. The Kerguelen Islands population is apparently distinct. These animals are larger than South American ones, and have shades of grey replacing black and white in the colour pattern.`,
        confusedWith: `The only other black and white small cetacean likely to be confused with this species is the spectacled porpoise, but the dorsal-fin shape and colour pattern differences should make these 2 easily discernable. In some areas, Commerson's dolphins may also be confused with black dolphins, which are mostly dark grey.`,
        size: `Length at birth ranges from 65 to 75 cm. Off South America, the adult size of Commerson's dolphin is up to 1.5 m and 66 kg; those off the Kerguelen Islands reach 1.75 m and 86 kg. Females are slightly larger than males in this species.`,
        distribution: `There are at least 2 disjunct populations of Commerson's dolphins, those off South America and the Falkland Islands, and those off the Kerguelen Islands. There are unsubstantiated reports of this species at South Georgia, but these are rejected by recent workers. Commerson's dolphins appear to prefer relatively shallow coastal waters, but some populations move slightly offshore in winter.`,
        behavior: `Small groups of less than 10 individuals are the norm for this species, although they do sometimes aggregate into groups of over 100. These are quick, active animals. They are known to ride bow waves and to engage in various types of leaps. Commerson's dolphins often swim upside down. The breeding season is in the southern spring and summer, September to February. Feeding is on various species of fish, squid, and shrimp. Commerson's dolphins appear to be opportunistic, feeding primarily near the bottom.`,
        exploitation: `Gillnet incidental catches probably represent the greatest threat to Commerson's dolphin populations, but they are also taken directly for crab bait in southern Chile. The effects of these kills on the populations involved are not known. Some Commerson's dolphins have been captured live in recent years, and the species appears to have done relatively well in captivity.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/commersonsDolphin/commersons-dolphin.jpg`
    },
    dallsPorpoise: {
        id: 13,
        name: `Dall's porpoise (Phocoenoides dalli)`,
        description: `These are robust animals, with a wide-based triangular dorsal fin, and small flippers placed near the head. The small head has a short beak, with no demarcation from the melon. From above, the head appears triangular. Dall's porpoises are strikingly marked, with a black body and bright white flank patches that are continuous ventrally, although young animals have muted colour patterns. The flank patches extend from the urogenital area to just in front of the dorsal fin, and up the sides about midway. In addition, there is white to light grey “frosting” on the upper portion of the dorsal fin and the trailing edges of the flukes. There are 2 commonly occurring colour types, the dalli-type (described and illustrated above) and the truei-type (which has a larger flank patch that extends to the level of the flipper). Dall's porpoise has the smallest teeth of any cetacean. There are 23 to 28 tiny spade-shaped teeth in each tooth row.`,
        confusedWith: `Dall's porpoises are likely to be confused only with harbour porpoises, and even then, only if seen at a great distance. When seen well, the differences in colour pattern and dorsal-fin shape will be readily apparent.`,
        size: `Newborn Dall's porpoises are about 1 m long. Adults are up to 2.2 m (females) or 2.4 m (males). Maximum weight is about 200 kg.`,
        distribution: `Dall's porpoises are found only in the North Pacific Ocean and adjacent seas. They inhabit deep waters of the warm temperate through subarctic zones, between about 30°N and 62°N. There is apparently a single truei-type population that migrates between the Pacific coast of Japan and the Okhotsk Sea; dalli-types predominate in all other areas of the range.`,
        behavior: `This may bethe fastest swimmer of all small cetaceans, at least for short bursts. When swimming rapidly, Dall's slice along the surface, producing a characteristic roostertail of spray. At other times, the animals move slowly and roll at the surface, creating little or no disturbance. These are avid bowriders, moving back and forth with jerky movements, and often coming from seemingly nowhere to appear at the bow of a fast-moving vessel. Breaching, porpoising, and other kinds of aerial behaviour, are extremely rare in this species. Dall's porpoises are found mostly in small groups of 2 to 12, although aggregations of up to several thousand have been reported. Groups appear to be fluid, often forming and breaking up for feeding and playing. Most Dall's porpoise calves are born in spring and summer. Dall's porpoises are opportunistic feeders, taking a range of surface and mid-water fish and squid, especially lanternfish and gonatid squid.`,
        exploitation: `The International Whaling Commission currently recognizes 8 stocks, based on pollutant loads, parasite faunas, and distribution patterns of cow-calf pairs. Heavy exploitation occurs in the western Pacific, both in a directed harpoon fishery and in several gillnet fisheries, in which Dall's are caught incidentally. The Asian driftnet fisheries for squid and salmon took several thousand anually in recent years in the central Pacific. Although there are records of small numbers being taken incidentally in the eastern Pacific, stocks there, unlike those in the central and western Pacific, are supposedly not in any immediate danger.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/dallsPorpoise/dalls-porpoise.jpg`
    },
    duskyDolphin: {
        id: 14,
        name: `Dusky dolphin (Lagenorhynchus obscurus)`,
        description: `The dusky dolphin is a small, moderately robust species. The rostrum is short and clearly demarcated from the melon (forehead). The conspicuous dorsal fin is moderately falcate and pointed. The flippers are moderately curved on the leading edge, with a blunt tip. The body coloration is complex, and is generally countershaded, dark grey to black above and white below. The sides are marked with blazes and patches of pale grey. In front of the dorsal fin, they bear a broad light grey thoracic patch that encompasses the face, most of the head, and flanks, tapering towardsthe belly. A separate crescent-shaped flank patch reaches the top of the tail stock just in front of the flukes. The front of this flank patch splits into 2 blazes, a shorter ventral and a longer dorsal one; this latter narrows and stretches up onto the back, almost to the blowhole. The rostrum is grey-black around the tip, tapering back to darken just the lips near the gape. The eye is set in a small patch of grey-black. A variable crescent of pale grey contrasts the trailing half of the dorsal fin with the dark coloured front half, and the flippers are pale grey, but darken around the edges. There are 27 to 36 small, pointed teeth on each side of each jaw.`,
        confusedWith: `At sea, dusky dolphins can be distinguished from the closely related, but larger and more robust, Peale's dolphin primarily by careful attention to differences in colour pattern.`,
        size: `The maximum recorded length is 2.1 m. Most adults are less than 2 m long. Healthy adults weigh 40 to 80 kg. Length at birth has been reported to be 55 to 70 cm.`,
        distribution: `Dusky dolphins are widespread in the Southern Hemisphere. They occur in apparently disjunct populations in the waters off New Zealand, South America, and southern Africa. This is a coastal species and is usually found over the continental shelf and slope.`,
        behavior: `Dusky dolphins are highly social, gregarious animals. They sometimes form impressive herds of over 1000 individuals, but are more likely to occur in groups of 20 to 500. Dusky dolphins are one of the most acrobatic of dolphins, frequently leaping high out of the water, at times tumbling in the air. They readily approach vessels to engage in bowriding. Many species of cetaceans have been observed in association with dusky dolphins. In New Zealand and Argentina, calving is believed to peak in summer (November to February). Dusky dolphins take a wide variety of prey, including southern anchovy and mid-water and benthic prey, such as squid and lanternfishes. They may also engage in nocturnal feeding. Cooperative feeding is practiced commonly in some areas.`,
        exploitation: `In New Zealand, some dusky dolphins are entangled in gill nets. Incidental mortality at one fishing port is estimated to be 100 to 200 animals per year. The situation in Peru is of greater concern. It has been calculated that the fishing industry from just one port kills more than 700 dusky dolphins each year. These dolphins are sold for food, so they are taken incidentally and as deliberate targets. Dusky dolphins are assumed to be relatively abundant throughouttheir range. However, very few surveys have been conducted and no population estimates are available.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/duskyDolphin/dusky-dolphin.jpg`
    },
    falseKillerWhale: {
        id: 15,
        name: `False killer whale (Pseudorca crassidens)`,
        description: `The false killer whale is one of several species of delphinids that some fishermen call blackfish. It has a long slender body, a rounded overhanging forehead, and no beak. The dorsal fin is falcate and slender, and generally somewhat rounded at the tip. The flippers have a characteristic hump on the leading edge, perhaps the species' most diagnostic character. This is a large, dark grey to black dolphin, with a faint light grey patch on the chest, and sometimes light grey areas on the head. Skulls of false killer whales from Australia, South Africa, and Scotland have been shown to differ, and this suggests the existence of different populations in these areas. Each jaw contains7 to 12 pairs of large conical teeth, which are round in cross-section.`,
        confusedWith: `False killer whales are most commonly confused with pygmy killer and melon-headed whales, and less commonly, pilot whales. Shape of the head, dorsal fin, and flippers will be the best characters to use in distinguishing them (the flipper hump of false killer whales is diagnostic).`,
        size: `Adults are up to 6 m (males) or 5 m (females) long. Large males may weigh up to 2000 kg. Newborns are 1.5 to 2.1 m.`,
        distribution: `False killer whales are found in tropical to warm temperate zones, in deep offshore waters. They generally do not range further north or south 50° in either hemisphere.`,
        behavior: `As is the case for most of the tropical oceanic delphinids, this species is poorly known. In some areas, false killer whales take bait from longlines and thus irritate fishermen. Groups of 10 to 60 are typical, though much larger groups are known. This is one of the most common species involved in cetacean mass strandings. The false killer whale is a lively, fast-swimming cetacean, which often behaves more like the spritely smaller dolphins than other mid-sized cetaceans. No seasonality in breeding is known for the false killer whale. Although false killer whales eat primarily fish and cephalopods, they also have been known to attack small cetaceans and, on one occasion, even a humpback whale.`,
        exploitation: `Small numbers of false killer whales are taken in fishing nets and lines throughout their range, but only in Japan has there been a major catch. This is one of several species killed in the now infamous Iki Island drives, in which cetaceans are driven ashore and killed because they are held responsible for depleting an overfished stock of yellowtail amberjack (Seriola lalandi). A few may be shot by fishermen who regard them as competitors, and small numbers have been captured live off California and Hawaii. Incidental catches of small numbers occur in several areas.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/falseKillerWhale/false-killer-whale.jpg`
    },
    finlessPorpoise: {
        id: 16,
        name: `Finless porpoise (Neophocaena phocaenoides)`,
        description: `As the name implies, finless porpoises have no dorsal fin, and this is their most distinctive characteristic. In some ways, they resemble small, slender white whales. The head is beakless; the rounded forehead rises steeply from the snout tip. The body shape, in general, is more slender than in other porpoises. The finless porpoise is soft and mushy, and the neck is very flexible. Instead of a dorsal fin, the finless porpoise has an area of small bumps or tubercles on its back, running from just forward of midback to the tail stock. The trailing edge of the flukes is concave and the flippers are large, ending in rounded tips. Regional differences in body size and morphology have been documented, with Yangtze River animals apparently representing a separate stock. The common name that was used in the past, “finless black porpoise,” apparently resulted from descriptions of dead animals, after post-mortem darkening. In most areas, finless porpoises are grey in colour, with lighter areas on the throat and around the genitals. Older animals are generally lighter grey than juveniles. In the Yangtze River population, they are very dark grey, nearly black. Tooth counts range from 13 to 22 in each tooth row.`,
        confusedWith: `The smooth back of the finless porpoise should make it easy to distinguish from other species, such as the Irrawaddy dolphin, baiji, and Ganges River dolphin, which share parts of its range.`,
        size: `Adults of this species reach about 1.9 m in length (males are slightly larger than females). Finless porpoises are apparently about 70 to 80 cm at birth.`,
        distribution: `Warm, coastal Indo-Pacific waters, both fresh and marine, are home to the finless porpoise. The range runs from northern Japan to the Persian Gulf, including many rivers in the Asian subcontinent (one of the best known populations is in the Yangtze River of China).`,
        behavior: `Finless porpoises are generally found as singles, pairs, or in groups of up to 12, although aggregations of up to about 50 have been reported. Like other porpoises, their behaviour tends to be not as energetic and showy as that of dolphins. They do not ride bow waves, and in some areas appear to be shy of boats. Mothers have been seen carrying calves on the denticulated area on their backs. In the Yangtze River, finless porpoises are known to leap from the water and perform “tail stands.” Reproduction in most areas has not been well studied. Reports indicate that calving in the Yangtze River occurs between February and April, and in Japan it occurs between April and August. Small fishes, squids, and shrimps form the diet of finless porpoises. They also apparently ingest some plant material, including leaves and rice.`,
        exploitation: `Finless porpoises are known to be taken in various gillnet fisheries throughout their range, including the Yangtze River. They are also incidentally taken in beach seines in India. Direct exploitation with guns, harpoons, and “fish forks” used to occur in China, and previously some incidental catches were sold for human consumption in Japan. Pollution and habitat destruction may also be factors in the status of this species. Some porpoises have been captured live for aquariums in Japan.`,
        img: `${process.env.BASE_ROUTE}/img/mammals/img/dolphinsAndPorpoises/finlessPorpoise/finless-porpoise.jpg`
    }
}

module.exports = animals;