
const animals = {
    branchiostomaLanceolatum: {
        id: 1,
        name: `Branchiostoma lanceolatum`,
        description: `— Larval body elongated, flattened laterally. Gill region swollen, in an otherwise slender body. Transparent (when living), however not completely. Gill slits 6 to 19, depending on developmental stage. Maximum number of myotomes in the larval stage is 61, being attained early in larval life. The larvae stay in the pelagic for 75-200 days. The larvae alternate periods of active upward swimming with passive sinking in horizontal position with the mouth on the left side directed downwards. During the descend, food is collected, consisting of copepods, phytoplankton, suspended material and detritus (see Webb, 1974 and references therein). This alternating up- and downward movement enables the larvae to stay in the surface layers, and hence being subject to horizontal transport by sea surface currents. — Adult body elongated and laterally compressed, pointed at both ends; colour iridescent whitish, opaque and transparent, leaving the internal anatomy visible. No skin or scale. Mouth inferior, surrounded with 20-30 cirri. A persistent notochord is present from front to caudal end. B. lanceolatum is living in sand, gravels, or shell deposits, and displays a distinct preference for specific grain size; the distribution of suitable substrate thus influences the distribution of the species.`,
        size: `Length of larvae 1.5-5 mm; length of adult up to 60 mm.`,
        reproduction: `Gonads are formed in the second or third year. Prior to spawning, adults form dense congregations of lancelets in bottom deposits of specific permeability. The eggs are externally fertilized. The larvae develop in the sediment to the 1-6 pouch stage, before they ascend into the pelagic. Spawning in the North Sea takes place in June to July. The maximum age of adults is 5 to 6 years.`,
        depthRange: `The larvae live in the plankton for at least a part of this developmental stage; they occur from surface to bottom depth. The larvae perform diurnal vertical migration, migrating to the surface at sunset. However, diurnal vertical migration was not found in B. lanceolatum from the North Sea, probably due to turbulence (see Webb, 1975). — Adult B. lanceolatum are normally living in bottom deposits of neritic waters, from sublittoral to generally 30-40 m deep. `,
        distribution: `Entire North Sea, including Skagerrak and Kattegat. However, due to the restricted reproduction period and the restricted spatial distribution of the adults, the larval B. lanceolatum is rare in the plankton. There exist, for instance, different populations in the Kattegat and the German Bight. The species seems to be rare along the British east coast and is abundant in the Central and eastern North Sea (cf. Franz, 1927). Widely distributed along Northeast Atlantic coasts, from northern Norway (67°N) to the Mediterranean Sea and Black Sea (may be absent from the Atlantic Spanish coasts). Entered in the Indian Ocean after passage through the Suez Canal; widely distributed in the northern Indian Ocean and tropical Southwestern Indian Ocean along the East African coast (see Poss and Boschung, 1996). The Norwegian populations at 67°N (see Franz, 1927) and 60°N (Courtney, 1975) are the northernmost known for the species, as well as the genus.`,
        img: `${process.env.BASE_ROUTE}/img/lancelets/img/branchiostomaLanceolatum/branchiostoma-lanceolatum.jpg`
    }
}

module.exports = animals