const animals = {
    acanthomysisLongicornis: {
        name: `Acanthomysis longicornis`,
        description: `Generic features: Statocyst usually present. Carpo-propodus divided into 6-8 subsegments. Pleopods of male rudimentary; fourth with a very long exopod armed with "pincer" setae. Apex of antennal scale rounded. No sternal processes. Antennal scale with rounded apex. Endopod (and exopod) of uropod without spines. Outer margin of antennal scale with setae; terminal tooth absent. Telson linguiform; lateral margins of telson and apex armed with a graduated series of spines and a pair of median setae. Species: General appearance is long and slender with the abdomen nearly straight. Antennule with very long peduncle, second segment small, distal segment swollen and almost equal in length to the first. Antennal scale extending only slightly beyond the antennular peduncle, narrowly lanceolate with rounded apex, about eight times as long as broad, with an oblique suture cutting off the terminal portion. Eyes large and pyriform, somewhat widely separated and projecting considerably beyond the lateral margins of the carapace, eyestalk stout and hispid. Thoracic limbs with propodite usually three-segmented, the proximal one the longest, merus subequal in length to the carpus, nail distinct, long and very slender. Pleopods similar to those in the genus Neomysis. Fourth pleopod of the male reaching to the middle of the last abdominal somite, exopod two-segmented, with the first segment about seven times as long as the second, which terminates in two long, unequal, spinous setae of which the longer is twice as long as the segment. Telson elongate, entire, widely dilated at the base and then suddenly constricted with the distal portion linguiform, apex bluntly rounded, proximal margin armed in the region of the constriction with two spines on each side, posterior two-thirds of margin and apex densely armed with numerous, unequal spines arranged in series, with larger spines separated by series of three, four or five smaller ones gradually increasing in size distally. Apex with two small central spines clanked by two larger ones. These spines arming the telson are somewhat peculiar. The external sheath of the spine is suddenly thickened towards the distal end, reducing the lumen in such a way as to present the appearance of an axial line. This has led some observers to think that the tip of the spine was trigonal. Uropods with endopod nearly equal in length to the telson, swollen at the base and narrowing sharply distally, inner margin armed in the region of the statocyst with a row of very small spines, of which the distal two or three are considerably larger than the others; exopod long and narrow, one and a half times as long as the endopod. Pigment blackish brown, sparse.`,
        colour: `Blackish brown, sparse.`,
        size: `Adult up to 9 mm long.`,
        depthRange: `Hyperbenthic; from 8 to 150 m. Acanthomysis longicornis is a filter-feeder, living on very minute organisms and on detritus.`,
        distributionInTheNorthSea: `Southwestern North Sea.`,
        worldDistribution: `Atlantic < 26-55°N, Mediterranean, Indo-W Pacific; coastal to shelf. Widely distributed in the waters of the Mediterranean and off the shores of west Europe as far as north as the British Isles`
    },
    afromysisHansoni: {
        name: `Afromysis hansoni`,
        description: `Outer margin of distal segment of endopod of maxilla extremely long. Exopod of male 4th pleopod more than twice as long as endopod, its last segment very long, more than 4 times as long as preceding segment. Lateral margin of telson with spines throughout.`
    },
    amblyopsAbbreviata: {
        name: `Amblyops abbreviata`,
        description: `Species: Body somewhat robust. Carapace large and deeply produced laterally; cephalic region slightly inflated; anterior margin broadly rounded without rostral projection. Posterior border emarginate leaving most of the last thoracic somite exposed in dorsal view. Eyes rudimentary in the form of two large, separate, rhomboidal plates. Antennular peduncle short and robust, outer distal corner of first segment produced as in the Genus Erythrops and tipped with three of four plumose setae; middle segment very short; Antennal peduncle slightly shorter than the antennular peduncle and much more slender, four-segmented, with the second short and bent upward from the plane of the first segment; third swollen, overhanging the second segment and bent downward from it so that in lateral view the peduncle has a peculiar distorted appearance. Uropod with exopod about twice as along as the last abdominal somite and half as long again as the slender, tapering endopod which bears a single blunt short spine on the inner ventral surface in the region of the statocyst. Telson linguiform, longer than the last abdominal somite; lateral margins tapering slightly to the bluntly rounded apex; posterior two-thirds of each lateral margin armed with a regularly graduated row of 26-27 spines which lengthen posteriorly and merge into the long spines at the apex; pair of median plumose setae present.`,
        colour: `Anterior portion of body transparent and colourless except for the eyeplates which are covered with very minute red specks of pigment and appear rosy red in colour. The large gut shows through the integument as a reddish mass and the yellow liver is also cleurly visible. The abdomen is sparsely covered with minute, evenly distributed, red specks.`,
        size: `Length of both sexes 18 mm.`,
        depthRange: `Hyperbenthic, bathypelagic; usually from 380 to 1425 m, with the greatest numbers occurring around depths of 600 m. Normally the species lives resting on the sea bottom making only short occasional excursions into the lower levels of water just above the floor.`,
        remarks: `Pleopods of the male very large and well developed, biramous, natatory.`,
        distributionInTheNorthSea: `Eastern northern North Sea, W off Norway, Skagerrak.`,
        worldDistribution: `N North Atlantic, N North Pacific; coastal to bathyal. N North Atlantic, N North Pacific; coastal to bathyal. Davis Strait, off west, south and east coasts of Greenland, south of Iceland, East Finmark, many records form Norwegian waters from Vardø to Oslofjord, Denmark, and from the Bay of Biscay.`
    },
    amblyopsKempi: {
       name: `Amblyops kempi`,
       description: `Generic features: Statocyst usually present. Pleopods of female reduced, rudimentary; of male variable. Endopod (and exopod) of uropod without spines. Outer margin of antennal scale without setae; ending in terminal tooth. Eyeplates quadrangular, outer corners rounded, margins not serrulated. Eyes often rudimentary in the form of flat plates without definite stalks. Telson rounded. Lateral margins of telson and apex armed with a graduated series of spines and a pair of median setae. Marsupium consists, as in the Genus Pseudomma, of two well-developed incubatory brood lamellae. Species: Body somewhat robust. Carapace slightly wider than the abdomen, anterior margin rounded to a bluntly rounded, very obtuse angle, cervical sulcus well marked, posterior margin emarginate. Eyes in the form of completely separated, broadly oblong, ocular plates; surface armed sparsely with minute spinules which are more dense and pronounced in the antero-lateral region; in larger specimens the plate is drawn out into a distinct lobe near the antero-distal angle. Antennal peduncle relatively short, equal in length to the antennular peduncle. First segment imperfectly divided, second segment overhanging the first dorsally making the peduncle appear distorted, especially in lateral view. Antennular scale about twice as long as the peduncle, tapering slightly towards the apex, with the widest part about one-third of the length of the scale from its proximal end; outer margin slightly convex, terminating in a prominent spine which extends beyond the apex of the scale and which may be armed with a small secondary spine on its inner margin; very large spine on the outer distal angle of the sympod. Uropod long and slender. Exopod more than one and a half times as long as the telson. Endopod shorter and more slender, usually armed with a single, long slender spine on the inner margin in the region of the statocyst. Telson equal in length to the last abdominal somite, narrowed abruptly close to the base, tapering very slightly to the broadly rounded, entire apex; apex armed with a median pair of minute spinules and two pairs of long slender spines which form the culmination of an evenly graduated series of 27-28 spines arming each lateral margin; a pair of plumose setae present above the median spinules.`,
       colour: `Similar to Amblyops abbreviata: anterior portion of body transparent and colourless except for the eyeplates which are covered with very minute red specks of pigment and appear rosy red in colour. The large gut shows through the integument as a reddish mass and the yellow liver is also cleurly visible. The abdomen is sparsely covered with minute, evenly distributed, red specks.`,
       size: `Length of both sexes up to 16 mm.`,
       depthRange: `Hyperbenthic, bathypelagic. The species occurs just clear of the bottom in depths of 700-1500 m. It is most abundant between 1100-1500 m.`,
       remarks: `Amblyops kempi can be distinguished from Amblyops abbreviata by: the presence of spinules all over the eyeplates, the particularly large spine on the basal joint of the antenna, the long slender spines on the endopod of the uropod and,  the shape and armature of the telson. Amblyops kempi is evidently a deeper water form than Amblyops abbreviata, but there is still overlap in the distributions of the two species. Amblyops kempi lives close to the sea bottom making only short occasional excursions into the lower levels of water just above the floor.`,
       distributionInTheNorthSea: `Probably rarae in the northern North Sea.`,
       worldDistribution: `North Atlantic, 44 - 64°N; shelf. Coastal to bathyal; e.g. west coast of Ireland, west of the Hebrides, Faeroes.` 
    }
};

module.exports = animals;